version: "3"
services: 
    develop:
        build: 
            context: .
            args: 
                PANDOC_VERSION: 2.14.0.3
        volumes: 
            - type: bind
              source: ./src/
              target: /jv-robot/src/
        working_dir: /jv-robot/
        command: [ "/bin/sh",  "-c", "while sleep 1000; do :; done"]